### PR TITLE
Readme and Relationships Added For Eloquent Implementation

### PR DESCRIPTION
**Pull request by saaiful**
Readme and Relationships Added For Eloquent Implementation

### CODE REVIEW

**Comment by CoolGoose** [comment]
Hi @saaiful i see a couple of issues

1. I'd wrap the optional ->with() in case it's empty 
2. Why are you loading the files manually after the autoloader ? 
3. I'm confused regarding the 'Displaying Data from Relationships ' part. You can just parse your php response nicely and specify the columns in vue-tables-2 already

**Comment by saaiful** [comment]
1. Fixed
2. Fixed
3. Because I was trying to pass a relation using with `$vuetables->get(User::with('user_metas'), [.id', 'name', 'email']);` and I was getting data without that relation.

**Comment by matfish2** [comment]
I agree with @CoolGoose regarding no. 3. 
I think it is enough to specify that you can use templates or child rows to display hierarchical data.
The exact presentation is for the user to decide according to his needs.

**Comment by molerat619** [comment]
How can I use this latest update?

**Pull request closed without merging**
