### PR TITLE
Feature drag rows

### PR DESCRIPTION
**Pull request by igor-sobolev**
New feature - rows can be draggable.

There's some new options in options object:
- **draggableRows**: false,
- **draggableCalback**: function draggableCalback(event) {},
- **draggableIdentity**: 'id'.

Dragging does not affect list of data, so to send REST request or update your list you should use _draggableCallback_, _draggableIdentity_ is used for key prop binding inside table to prevent rows shuffling, _draggableRows_ just enables rows to drag.

P. S. Sorry for auto formatting some files I touched to implement feature, but I couldn't see these trailing spaces and misindentation.

### CODE REVIEW

**Comment by matfish2** [comment]
Thanks for the PR, before I can check the functionality please resolve all merge conflicts by merging the most recent version into your branch and recompiling.

**Comment by matfish2** [comment]
Thanks for the PR. Before I can check functionality please fix merge conflicts by pulling the most recent version into your branch

**Comment by igor-sobolev** [comment]
Thanks for reply. If you don't want to use external packages, I don't insist on this pull req. I just needed that functionality in one enterprise project and saw some issues on github for requesting dragging rows/columns unanswered, so I forked repo and implemented for myself. Maybe you can leave this as solution for some people in docs, I don't know.

**Comment by jasonlfunk** [comment]
I personally would find this useful as well. My collections typically have a hidden "sort order" to organize them and it would be cool to be able to allow my users to update the order without having to edit each one individually. Perhaps there could be an additional option that limited the reordering to when the objects are sorted by a specific column. Like in my case: `draggableRowsWhenSortedBy: ["sort_order"]`.

**Pull request closed without merging**
