### PR TITLE
fix the date picker implementation with vuex, add package-lock from npm5

### PR DESCRIPTION
**Pull request by CoolGoose**

### CODE REVIEW

**Comment by CoolGoose** [comment]
@matfish2 
This fixes the date filter to send the correct data into the server implementation when vuex is used.
The fix seems to be a bit of a hack if you look at the server-search.js 'tweak' but I guess we can discuss and plan a refactor for that.

It also includes a .lock file from npm5.

Since it's constantly compiling more than it should from the different babel settings, can you share yours in the repo so there's less noise in the merges ?

**Comment by matfish2** [comment]
Merged. 

`Babel --v` returrns

`6.16.0 (babel-core 6.17.0)`

.babelrc

```js
{
  "presets": ["es2015"],
  "plugins": ["transform-vue-jsx"]
}
```

**Comment by matfish2** [comment]
On 'init-date-filters.js' line 29 you added:

```js
 el.text(drp.startDate.format(that.opts.dateFormat) + " - " + drp.endDate.format(that.opts.dateFormat));
```

This causes the filter to load with a range of "today - today" instead of the "Filter by date" placeholder. Is there any reason for this addition I'm not aware of?

**Comment by CoolGoose** [comment]
@matfish2 actually no, it's a bug on my end, I've updated it on #194

**Pull request merged**
