### PR TITLE
fix #25 (responseAdapter prop)

### LINKED ISSUE #25: Using it with an existing server that I can't be changed
Hi,

I am wondering if I can make an adapter. Can I specify a function instead of a server url to return the results to populate the table?

My server has the same features needed: pagination, filter, etc. But with different names and different return.

If I could use the client side mode but specifying the total number of pages would be ok too.

Thanks

### PR DESCRIPTION
**Pull request by melanke**
How to use it:
```
<template>
    <div class="table-responsive">
        <v-server-table url="MyUrl" :columns="columns" :responseAdapter="respAdapter"></v-server-table>
    </div>
</template>

<script>
export default {
    data: function() {
        return {
            columns: ['field1','field2'],
            respAdapter: function(data) {
                return data.data;
            }
        };
    }
}
</script>
```

### CODE REVIEW

**Comment by matfish2** [comment]
Thank you for this PR. 

Before I merge I would like you to change two things:

1. `responseAdapter` should be an option (set it in `config/defaults.js`), not a prop.
2. The default implementation should return the data as-is, thus eliminating the need for the conditional on line 61.

**Comment by melanke** [comment]
And I noticed a bug in pagination, it should be used inside get-data, I will fix those things

**Comment by melanke** [comment]
Is that ok?

**Comment by matfish2** [comment]
So it seems. I will merge and test it.

**Pull request merged**
