### PR TITLE
Custom column styling

### PR DESCRIPTION
**Pull request by gozcan**
can be configured in opts:
columnClass:{
columnName: className
}

### CODE REVIEW

**Comment by matfish2** [comment]
Why not use CSS pseudo-selectors (`:nth-child`) instead?

**Comment by gozcan** [comment]
Yes you can do that but it makes more sense to me this way as I don't need to deal with column counts and numbers. Plus we can use pre-defined classes.

**Comment by matfish2** [comment]
I personally don't see a lot of benefit to this one. IMHO it is more simple and elegant to use pseudo-selectors, without contaminating the table with so many unnecessary classes. So, thank you, but I think I'll pass on this one unless convinced otherwise.

**Comment by cihadturhan** [comment]
Apologies for resurrecting this issue again but I believe this feature is a need.

`:nth-child` does not work when you need dynamic columns to be added or removed. Consider the following case:

Base Table
`| Column 1 | Column 2 | Column 3 | Column 4| Column 5 |`
User doesn't need column 3 so we user removes it dynamically
`| Column 1 | Column 2 | Column 4| Column 5 |`

Now, our `:nth-child` selectors will fail.

**Comment by seansean** [comment]
Agreed. I have a use case where a column that requires a specific style can appear in different positions depending on the user or the page on which the table appears. nth-child won't work in this case.

**Comment by catheibasilio** [comment]
hi , i need help on columnClasses , in case i need to add a class to a td that has negative or positive number on.

without the vue-tables-2 my ternary condition is like this.: 
```
<td
                class="text-right"
                :class="{'text-danger': (Math.sign(column1 < 0),
              'text-success': (Math.sign(column1) > 0)}"
              >{{ percent }} %</td>
```

please help!

**Comment by catheibasilio** [comment]
to add a class indicator warning i have updated the code -- and this doesn't seem to work , am i missing anything?
`<div id="mutual-fund" class="sc-small mb-0">
          <v-client-table
            v-if="tableData.length > 0 && tableData"
            :data="tableData"
            :columns="columns"
            :options="options"
            :columnsClasses="columnsClasses"
          >
            <template slot="mfpl" scope="props">
              <div v-if="Math.sign(mfpl) > 0" class="text-sucess">{{ props.row.unrealisedPL }}</div>
            </template>
          </v-client-table>
        </div>`

**Comment by catheibasilio** [comment]
thank you so much for your response!

do i have to enclose the span in a template block? or the span slot is sufficient?

this is now my code, i added the span slot & methods ::: however i still don't see that the class is being applied. 
```
  <div class="p-2">
    <div class="my-1">
      <div class="mx-2 border rounded">
        <div class="p-2 sc-smaller text-uppercase">Mutual Fund</div>
        <div id="mutual-fund" class="sc-small mb-0">
          <v-client-table v-if="tableData.length > 0 && tableData" :data="tableData" :columns="columns" :options="options">
           
               <span slot="mfpl" slot-scope="props"
                      :class="getNegativeValueClass(props.row.mfpl)">
                    {{ props.row.unrealisedPL }}
                </span>

          </v-client-table>
        </div>
      </div>
    </div>
  </div>
```

```methods: {
      getNegativeValueClass(value) {
        return Math.sign(value < 0) ? 'text-danger' : 'text-success'
      }
    }```

**Comment by catheibasilio** [comment]
```<template>
  <div class="p-2">
    <div class="my-1">
      <div class="mx-2 border rounded">
        <div class="p-2 sc-smaller text-uppercase">Mutual Fund</div>
        <div id="mutual-fund" class="sc-small mb-0">
          <v-client-table v-if="tableData.length > 0 && tableData" :data="tableData" :columns="columns" :options="options">
            <span slot="mfpl" slot-scope="props"
                      :class="getNegativeValueClass(props.row.mfpl)">
                    {{ props.row.unrealisedPL }}
                </span>
          </v-client-table>
        </div>
      </div>
    </div>
  </div>
</template>
        

<script>
  import axios from 'axios'
  import vue from 'vue'
  import ClientTable from '../../node_modules/vue-tables-2'
  import moment from 'moment'
  import numeral from 'numeral'
  vue.component('v-client-table', ClientTable)
  
  export default {
    name: 'ClientPortfolio',
    props: ['id', 'name', 'isStaff', 'riskRating'],
  
    data: function() {
      return {
        mfdata: [],
        rId: this.id,
        columnsClasses: '',
        columns: [
          'att2',
          'att1',
          'att3',
          'att4',
          'att5',
          'unrealisedPL',
          'att6'
        ],
        tableData: [],
        options: {
          filterable: false
          },
          columnsClasses: {
            unrealisedPL: 'mfpl',
            att1: 'fname',
            att2: 'att2-pr',
            att3: 'att3-date',
            att4: 'att4-bal',
            att5: 'att5-cost',
            att6: 'att6-perc'
          },
          sortable: [],
          headings: {
            att1: 'Fun',
            att2: 'PR',
            att3: 'Date',
            att4: 'Fees',
            att5: 'Value',
            unrealisedPL: 'profit/loss',
            att6: ' %'
          }
        }
      }
    },
    methods: {
      getNegativeValueClass(value) {
        console.log('value', value);
        return Math.sign(value < 0) ? 'text-danger' : 'text-success'
      }
    },
    mounted() {
      axios
        .get('api/s/' + this.rId)
        .then(res => {
          this.tableData = res.data
          console.log('tabledata', this.tableData)
        })
        .catch(error => {
          console.log('error', error.response)
        })
    }
  }
</script>

<style>
  
</style>
```

**Comment by catheibasilio** [comment]
thank you so much!!

**Pull request closed without merging**
