### PR TITLE
Cache state with Vuex

### PR DESCRIPTION
**Pull request by dannydombrowski**
On the initialization of the VueTable, using Vuex, the store was being overriden everytime.

* Added a condition to check if wheter to override the store or not
* Added a configuration option to enable the cache, by default the cache is disabled

### CODE REVIEW

**Comment by matfish2** [comment]
I didn't understand the issue. What do you mean by the store being overidden? I am using the register module call only once, on `created`, to register the module on the existing store.

**Comment by dannydombrowski** [comment]
True, I didn't explain my purpose, my bad.

While using VueRouter, you may navigate in your SPA and return to a route where vue-tables was loaded, from that point the created method in v-server-table.js while be called again, overwriting the registered module with a new, empty, one, making Vuex useless.

**Comment by matfish2** [comment]
Good catch. Merged.

**Comment by kife-design** [comment]
I see that the cache option is gone again. I'm having the same problem as explained here, when i navigate to another page with vue-router, and return back to a route where vue-table is active, then my store loses all its actions. Ive set the saveState option to true, but that didnt help.

**Pull request merged**
